[package]
name = "pavo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pavo"
path = "src/main.rs"

[lib]
name = "pavo"
path = "src/lib.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
rustc-hash = "2.0"
rand = "0.8"
pest = "2.7"
pest_derive = "2.7"
lazy_static = "1.5"
